name: 'Generate Docker Tag'
description: 'Generate next Docker image tag from git tags'
outputs:
  new_tag:
    description: 'Generated Docker tag'
    value: ${{ steps.version.outputs.new_tag }}

runs:
  using: composite
  steps:
    - name: Generate Docker image tag
      id: version
      shell: bash
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)
        NEW_TAG="v1-${SHORT_SHA}"
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        
        
