name: 'Generate Docker Tag'
description: 'Generate next Docker image tag from git tags'
outputs:
  new_tag:
    description: 'Generated Docker tag'
    value: ${{ steps.generate.outputs.new_tag }}

runs:
  using: composite
  steps:
    - name: Generate Docker image tag
      id: generate
      shell: bash
      run: |
        NEW_TAG="v$(date +'%Y.%m.%d-%H%M%S')"
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
